version: "3.6"

services:
  dhis2-core:
    image: dhis2/core-dev:jib-2.39-SNAPSHOT
    ports:
#      - 8080:9080
      - 8080:8080
    environment:
      JAVA_TOOL_OPTIONS: "-Djetty.host=0.0.0.0"
      DHIS2_HOME: /dhis2
    volumes:
      - ./config/dhis.conf:/opt/dhis2/dhis.conf:rw
      - ./dhis2_home:/dhis2:rw

  db:
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSOWRD: dhis

  dhis2-base:
    image: tons/dhis2-base
    build:
      context: .
      dockerfile: Dockerfile.base

#  tomcat:
#    image: tomcat:8.5-jre11-openjdk
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./config/dhis.conf:/opt/dhis2/dhis.conf:rw
#      - ./config/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
#      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
#      - /home/tons/IdeaProjects/dhis2/dhis2-core/dhis-2/dhis-web/dhis-web-portal/target/dhis.war:/usr/local/tomcat/webapps/dhis2.war
