version: "3.6"

services:
  dhis2-core:
    image: dhis2/core-dev:jib-2.39-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
#      JAVA_TOOL_OPTIONS: "-DCONTEXT_PATH='/whatever'"
      DHIS2_HOME: /dhis2
    volumes:
      - ./config/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./dhis2_home:/dhis2:rw

  db:
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
